# Training configuration
output_dir: "/ssd-shared/yichen_models/clinical_bert_readmission"

# Training parameters
train_batch_size: 16
eval_batch_size: 32
learning_rate: 2e-5
num_train_epochs: 3
warmup_steps: 500
weight_decay: 0.01

# Training optimization
fp16: true
dataloader_num_workers: 4
save_strategy: "epoch"
eval_strategy: "epoch"
load_best_model_at_end: true
metric_for_best_model: "eval_f1"
early_stopping_patience: 2

# Logging
logging_steps: 100
save_total_limit: 3
greater_is_better: true
report_to: null